#:kivy 1.11.1

BoxLayout:
    orientation: 'vertical'
    
    Label:
        text: 'Terminal carrorama'
        size_hint_y: 0.2

    Butoes:
        text: 'Cadastrar veiculo'
        pos_hint: {'x': 0.5}
        on_press: root.cadastra_veiculo_trigger()
        

    Butoes:
        text: 'Relatorios'


<Butoes@Button>:
    background_normal: ''
    background_color: 0, 150, 107, 1
    background_down: ''
    size_hint_y: 1
    size_hint_x: 0.5
    
            